sudo: false
language: go

env:
  matrix:
    - GO111MODULE=on

go:
  - 1.13.x

before_script:
  - go mod download

script:
  - go get -u ./...
  - go test ./...

branches:
  only:
    - master

matrix:
  fast_finish: true
